name: Build (Windows)

on: push

jobs:
  build:
    runs-on: windows-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Setup build cache
        uses: pat-s/always-upload-cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build project using Gradle
        run: ./gradlew build -x test --stacktrace --scan

      - name: Download shared libs
        run: ./gradlew :downloadLibs

      - name: Move shared libs to the root directory
        run: cp libs/*.dll .

      - name: Check dependencies
        run: |
          ldd src/main/resources/lib/win64/jminisat.dll
          ldd src/main/resources/lib/win64/jglucose.dll
          ldd src/main/resources/lib/win64/jcms.dll
          ldd src/main/resources/lib/win64/jcadical.dll

      - name: Download CryptoMiniSat
        run: |
          mkdir bin
          cd bin
          wget https://github.com/msoos/cryptominisat/releases/download/5.8.0/cryptominisat5-win-static.zip
          unzip cryptominisat5-win-static.zip

      - name: Add Cryptominisat to PATH
        run: echo "$(realpath bin)" >> $GITHUB_PATH

      - name: Run tests
        run: ./gradlew cleanTest test --no-build-cache --stacktrace

      - name: Run application
        run: ./gradlew run

      - name: Stop Gradle daemon
        run: ./gradlew --stop
